logging:
  level.root: INFO
  level.no: ${LOG_LEVEL:DEBUG}
application:
  fusekiService: http://fuseki:8080/fuseki
  referenceDataUrl: http://reference-data:8080
  searchApiHostname: ${SEARCH_API_HOST:https://www.fellesdatakatalog.brreg.no/}
elastic:
  clusterNodes: ${FDK_ES_CLUSTERNODES:elasticsearch5:9300}
  clusterName: ${FDK_ES_CLUSTERNAME:elasticsearch}

---
#Utv-miljø lokalt på egen PC
spring:
  profiles: develop, unit-integration
application:
  referenceDataUrl: http://localhost:8112 #http://localhost:8113
  fusekiService: http://localhost:3030/fuseki
elastic:
  clusterNodes: localhost:9300
  clusterName: elasticsearch
server:
  port: 8119
